# Generated by Django 4.2.18 on 2025-01-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='cheque_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
