# Generated by Django 4.2.18 on 2025-01-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_merchantcategory_remove_expenses_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='merchant',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='merchantcategory',
            name='merchant',
            field=models.CharField(max_length=200),
        ),
    ]
