# Generated by Django 4.2.18 on 2025-02-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expenses_merchant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('essential', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('non_essential', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
