# Generated by Django 4.2.18 on 2025-02-02 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
