import regex
import os

app_dir = os.path.dirname(os.path.realpath(__file__))
data_path = os.path.join(app_dir, "data", "complaint_training_data.csv")
embedding_path = os.path.join(app_dir, "data", "embeddings.csv")

EMBEDDING_MODEL="all-MiniLM-L12-v2"
RE_BAD_CHARS = regex.compile(r"[\p{Cc}\p{Cs}]+")

mapping_dict = {'Device': {'Damaged / Broken': ['Medium', 'High'], 'Defective Component': ['Medium', 'High'],
                           'Defective Device': ['Medium', 'High'], 'Device Malfunction': ['Medium', 'High'],
                           'Incorrect Component/Device': ['High'], 'Leaking': ['Medium', 'High'],
                           'Missing Component/Device': ['Medium', 'High'], 'Needle Stick/Prick': ['Medium'],
                           'Safety Device Issue': ['High']}, 'Primary Container/Closure':
    {'Broken Plunger Rod': ['Medium', 'High'], 'Cannot Push Plunger': ['Medium'],
     'Child Resistant Cap (CRC) Failure/Missing': ['Medium', 'High'], 'Damaged/ Defective Seal': ['Medium', 'High'],
     'Damaged/Broken': ['Medium', 'High'], 'Damaged/Defective container (non- sterile)': ['Medium', 'High'],
     'Damaged/Defective container (sterile)': ['High'], 'Defective ': ['Medium', 'High'],
     'Defective pump/dose counter': ['Medium', 'High'], 'Leaking': ['Medium'], 'Loose': ['High', 'Medium'],
     'Missing Plunger Rod': ['High'], 'Missing Seal': ['Medium'], 'Missing/damaged Cotton /Rayon wool ': ['Low'],
     'Missing/damaged Desiccant': ['Medium'], 'Packaging burned': ['Medium'],
     'Primary Packaging / Container Difficult to Open': ['Medium'], 'Stopper Coring': ['Low'],
     'Stopper Dislodge': ['Medium']},
     'Secondary Packaging': {'Carton/Packaging Damaged/Defective': ['Low', 'Medium'],
                             'Component - Difficult to Remove': ['Medium'], 'Component – Missing': ['Medium'],
                             'Component – Seal Not Intact': ['Medium'], 'Mismatch': ['High'],
                             'Missing/Damaged Tamper Evident Seal': ['Medium', 'High'],
                             'Package Difficult to Open': ['Medium'], 'Packaging - Burned': ['Medium'],
                             'Seal Missing': ['Medium']},
    'Labeling': {'Confusing': ['Low'], 'Damaged label': ['High', 'Medium'],
                 'Damaged leaflet/ Package Insert': ['Medium'], 'Incorrect information on Package Insert ': ['High'],
                 'Incorrect Information on the label': ['High'], 'Incorrect leaflet/Package Insert': ['High'],
                 'Mismatch': ['High'], 'Missing Label': ['High'], 'Missing leaflet/Package Insert': ['High'],
                 'Missing Text / Variable data': ['High'], 'Peeling': ['Medium'],
                 'Serialization/barcode Issue': ['High'], 'Text Illegible ': ['Medium']},
                'Market Events': {'Artwork Incorrect ': ['High', 'High'], 'Stolen/Diverted': ['High'],
                                  'Suspected Counterfeit': ['High'], 'Suspected Falsification': ['High'],
                                  'Suspected Tampering': ['High']},
                'Foreign Matter': {'Dirt in/on product': ['High'], 'Fiber in/on product': ['High'],
                                   'Glass in/on product': ['High'], 'Hair in/on product': ['High'],
                                   'Insect in/on Product': ['High'], 'Metal in/on product': ['High'],
                                   'Miscellaneous Sources of contamination in/on Product': ['High'],
                                   'Plastic in/on product': ['High'], 'Rubber in/on product': ['High'],
                                   'Component – Foreign Material': ['High'], 'Foreign matter on packaging': ['High'],
                                   'Product - Particles': ['High']},
                'Drug Effect': {'Elevated Effect': ['Low'],'Lack of Effect': ['Low']},
                'Product': {'Abnormal consistency ': ['High'], 'Administering Difficulty': ['Medium'],
                            'Agglomerate': ['High', 'Low'], 'Bacterial Meningitis': ['High'], 'Catheter Break': ['Medium'],
                            'Catheter Disconnection': ['Medium'], 'Catheter Fracture': ['Medium'], 'Catheter Kink': ['Medium'],
                            'Catheter Migration': ['Medium'], 'Catheter Occlusion': ['Medium'], 'Cerebrospinal Fluid Infection': ['High'],
                            'Cerebrospinal Fluid Leakage': ['High'], 'Chewability': ['Medium'], 'Count - Long Count': ['Medium'],
                            'Count - Short Count': ['Medium'], 'Dissolution or Disintegration Issue/Insoluble': ['Medium'],
                            'Double Capped': ['Medium'], 'Empty Blister/Bottle': ['Medium', 'High'],
                            'Flow Difficulty': ['Medium'], 'Half Capsule': ['Low'],
                            'Imprint/ Printing/ Embossing Defect / Missing / incorrect': ['High'], 'Incomplete Diluent Transfer': ['Medium'],
                            'Infection (General/ Unspecified)': ['High'], 'Manufacturing Defect': ['High'], 'No diluent Transfer': ['Medium'],
                            'Occluded Orifice': ['High'], 'Product - Appearance': ['High'], 'Product - Mismatch': ['High'],
                            'Product– Broken/ Cracked/ Damaged': ['Medium', 'High'], 'Product- Missing': ['Medium', 'High'], 'Product -Odor': ['High'],
                            'Reconstitution Difficulty': ['Medium'], 'Solution Appearance Issue': ['High'], 'Too Thick/Viscous ': ['High'],
                            'Unable to Aspirate Cerebrospinal Fluid': ['High'], 'Unusual Taste/Odor ': ['Low', 'High'],
                            'Volume – Empty*': ['Medium'], 'Volume – Overfilled*': ['Medium'], 'Volume – Varied*': ['Medium'],
                            'Volume- Underfilled*': ['Medium'], 'Withdrawing Difficulty': ['Medium'], 'Wound Infection': ['High']},
                'Administration Set': {'Backflow': ['High'], 'Pump – Interface Incompatible': ['Medium']},
                'Non-complaint': {'Adverse Event Only ': ['Low'], 'Customer Suggestion': ['Low'], 'Duplicate': ['Low'],
                                  'False Falsified Medicines Directive (FMD) Alert': ['Low'], 'Inquiry': ['Low'],
                                  'No Product Quality Issue Reported ': ['Low'], 'Not a Takeda Product': ['Low'],
                                  'Not a Takeda Component ': ['Low'], 'Parallel Import not a Takeda process ': ['Low'],
                                  'Product Replacement Requests Only': ['Low'], 'Shipping/Handling/ Ordering Issue': ['Low']},
                'User': {'Expired Product': ['Low'], 'Failure to follow instructions': ['Low'], 'Improper Storage Conditions': ['Low'],
                         'Substitute Component Used': ['Low'], 'Wrong Component': ['Low'], 'Wrong Dosage': ['Low']},
                'Software Application': {'Non-Complaint – Customer Suggestion': ['Low'], 'Non-Complaint – Duplicate': ['Low'],
                                         'Non-Complaint – Inquiry': ['Low'], 'Non-Complaint – Not a Takeda Product': ['Low']},
                'Transport': {'Logger Issues': ['Low'], 'Shipper Damaged': ['Low'], 'Shipper Defective ': ['Low'],
                              'Short Filled Shipper': ['Low'], 'Temperature Deviation': ['Low']},
                'Tertiary Packaging': {'Damaged Shipper': ['Low'], 'Short filled shipper': ['Low']}}